kind: pipeline
type: docker
name: default

steps:
- name: build
  image: maven
  commands:
  - mvn package --batch-mode
- name: docker
  image: plugins/docker
  settings:
    registry: ghcr.io
    username: ngoriyasjil
    password:
      from_secret: registry_pass
    repo: ghcr.io/ngoriyasjil/tnilgloss
    tags: latest
  when:
    repo:
    - ngoriyasjil/TNILGloss
- name: webhook
  image: plugins/webhook
  settings:
    urls:
      from_secret: webhook_url
  when:
    repo:
    - ngoriyasjil/TNILGloss
